### ISSUE TITLE
有个关于sails的问题

### ISSUE THREAD

**Issue by scgy5555** [koukuko/Rikka#1]
敬爱的光驱，我是通过你接触到的sails，目前已经上线了两个项目
但是遇到一个小问题找不到人交流，如果您有时间希望能帮我解答

我的需求是sails对多数据库进行联合查询
可能是两个mysql或者两个mongodb，从完全不一样的表结构中取出数据
问题在于我不知道怎么操作多数据库

sails有相关功能吗？还是有什么能推荐的node多数据库操作的方式？

**Comment by koukuko** [comment]
@scgy5555 
如果是一个model仅用于一个数据库 [你可以在model setting中设置使用的connection](http://sailsjs.org/documentation/concepts/models-and-orm/model-settings#?connection) 以达到使用多个数据库的的目的，
如果是一个model使用多个数据库，好吧，同个类型数据请用集群链接，不同类型的自求多福。

**Comment by scgy5555** [comment]
感谢！
