### ISSUE TITLE
关于sails请问怎么能实现多级populate查询

### ISSUE THREAD

**Issue by scgy5555** [koukuko/Rikka#2]
很抱歉又打扰了，能不能留个qq请你喝咖啡。
问题是这样的，有一个多级关联的数据，当我使用populate参数时只能获取到第一级的关联内容

例如:
GET /api/quotation?populate[]=owner&populate[]=customer

```
quotation: {
  owner: {/* 内容 */}
  customer: {
   owner:1
  }
}
```

期望是连同customer中的owner也获取到
这个model和quotation中的owner是同一个model

**Comment by koukuko** [comment]
@scgy5555 
这两天肝ps4去了一直没看邮箱。
这个问题我没想到什么可以直接利用sails的解决方案，恐怕只能利用这个了。https://github.com/balderdashy/waterline-docs/blob/master/models/instance-class-methods.md#instance-methods

**Comment by scgy5555** [comment]
额，现在回复居然没有提示了。。
额外用一个属性去读取我确实有这么用，就是感觉有点不符合逻辑，老外难道没有这么用的吗？
还是非常感谢，说真的不给个联系方式来一发……技术交流吗，或者有什么推荐的node群
